services:
  debtools:
    build:
      context: .
      dockerfile: Dockerfile.debtools
    volumes:
      - ../../:/workspace-parent
      - ../:/workspace
    working_dir: /workspace
    command: /bin/bash
